import json,re
from pathlib import Path
r=Path(__file__).resolve().parent/'tarot'
major=[
('Głupiec','Nowy początek i gotowość do próby. Zostaw miejsce na doświadczenie.','Pośpiech lub nieuwaga. Sprawdź grunt, zanim zrobisz kolejny krok.','początek'),
('Mag','Masz narzędzia i możliwość działania. Połącz pomysł z konkretną czynnością.','Rozproszone umiejętności albo efektowność bez treści. Uporządkuj zamiar.','działanie'),
('Kapłanka','Cisza i uważna obserwacja. Daj czas temu, czego jeszcze nie rozumiesz.','Domysł może przesłaniać to, co widoczne. Wróć do obserwacji.','obserwacja'),
('Cesarzowa','Rozwój i pielęgnowanie pomysłu. Zadbaj o warunki, w których może dojrzeć.','Nadmiar troski lub brak przestrzeni. Sprawdź, co naprawdę potrzebuje uwagi.','rozwój'),
('Cesarz','Struktura i granice. Ustal reguły, dzięki którym można spokojnie pracować.','Sztywna reguła utrudnia zmianę. Rozważ, którą granicę warto rozluźnić.','struktura'),
('Kapłan','Tradycja, nauka i wspólne zasady. Sprawdź, czego uczą wcześniejsze doświadczenia.','Cudzy schemat może nie pasować. Nazwij własne kryterium wyboru.','tradycja'),
('Kochankowie','Spotkanie dwóch możliwości. Wybierz w zgodzie z tym, co jest dla Ciebie ważne.','Rozbieżne zamiary wymagają rozmowy. Uporządkuj, co chcesz ze sobą połączyć.','wybór'),
('Rydwan','Ukierunkowana energia. Ustal cel i skoordynuj różne siły.','Sprzeczne kierunki zużywają siłę. Zwolnij i ustal priorytet.','kierunek'),
('Siła','Cierpliwość i łagodne opanowanie. Wytrwałość może działać lepiej niż nacisk.','Nacisk zastępuje spokój. Odpocznij i zmień sposób działania.','cierpliwość'),
('Pustelnik','Skupione poszukiwanie. Oświetl mały fragment problemu, zamiast obejmować wszystko.','Izolacja zawęża perspektywę. Wprowadź drugi punkt widzenia.','namysł'),
('Koło Fortuny','Zmiana warunków i powtarzalny rytm. Zauważ, co wraca, a co jest nowe.','Przywiązanie do starego cyklu. Zastanów się, gdzie możesz przerwać powtórzenie.','zmiana'),
('Sprawiedliwość','Równowaga i odpowiedzialność za wybór. Porównuj według tych samych zasad.','Nierówne kryteria zaburzają ocenę. Sprawdź własne założenia.','równowaga'),
('Wisielec','Pauza i inny punkt widzenia. Spróbuj spojrzeć na układ po obrocie.','Zawieszenie bez celu. Ustal, jaką nową obserwację ma przynieść przerwa.','perspektywa'),
('Śmierć','Zamknięcie etapu i zmiana formy. Zrób miejsce dla nowego układu.','Trzymanie się zakończonego etapu. Nazwij to, co trudno odłożyć.','przemiana'),
('Umiarkowanie','Łączenie i dobór proporcji. Sprawdź, czy elementy wspierają się wzajemnie.','Składniki nie współgrają. Zmieniaj jedną proporcję naraz.','łączenie'),
('Diabeł','Przywiązanie i nawyk. Zauważ, co ogranicza swobodę wyboru.','Rozluźnienie więzi. Sprawdź, z którego przyzwyczajenia możesz zrezygnować.','przywiązanie'),
('Wieża','Nagłe naruszenie dotychczasowego układu. Zbadaj, na czym stała konstrukcja.','Odkładana zmiana. Sprawdź słabe miejsce, zanim dołożysz kolejną warstwę.','przełom'),
('Gwiazda','Spokojna nadzieja i odnowa. Wybierz mały krok, który przywraca kierunek.','Zniechęcenie osłabia zaufanie. Wróć do osiągalnego działania.','nadzieja'),
('Księżyc','Niejasność i wyobraźnia. Zapisz wrażenie, ale pozostaw je otwarte na sprawdzenie.','Mgła może się przerzedzać. Oddziel obawę od tego, co zaobserwowano.','niejasność'),
('Słońce','Jasność i radość odkrywania. Pokaż pomysł w prosty, czytelny sposób.','Chwilowe przygaszenie lub nadmierna pewność. Sprawdź, czego jeszcze nie widać.','jasność'),
('Sąd Ostateczny','Ponowna ocena i odpowiedź na wezwanie. Wróć do wcześniejszego wyboru.','Odkładanie decyzji. Nazwij, co jest potrzebne do rzetelnej oceny.','przegląd'),
('Świat','Domknięcie i połączenie całości. Zobacz, jak części tworzą większy układ.','Niedokończony etap. Poszukaj brakującego połączenia przed zamknięciem.','całość')]
suits={
'wands':('Buław','działanie',[
('Impuls do działania i świeży pomysł. Wypróbuj pierwszy krok.','Zapał potrzebuje kierunku. Zmniejsz zakres próby.'),('Planowanie dalszej drogi. Porównaj dostępne możliwości.','Wahanie opóźnia start. Wybierz małą odwracalną próbę.'),('Poszerzanie horyzontu. Zobacz, dokąd prowadzi rozpoczęty wysiłek.','Oczekiwania wyprzedzają wyniki. Sprawdź etap pośredni.'),('Wspólna podstawa i chwila świętowania. Uporządkuj osiągnięty etap.','Brakuje oparcia lub zgody. Zadbaj o wspólną podstawę.'),('Różne siły spotykają się w sporze. Porównaj ich cele.','Unikanie sporu ukrywa różnice. Nazwij je spokojnie.'),('Widoczny postęp i uznanie. Sprawdź, co rzeczywiście zadziałało.','Potrzeba uznania przesłania pracę. Wróć do własnych kryteriów.'),('Obrona stanowiska. Wskaż, na czym opierasz swoją pewność.','Przeciążenie obroną. Rozróżnij ważne granice od drobnych sporów.'),('Szybki przepływ i ruch. Utrzymaj czytelną kolejność działań.','Zbyt wiele naraz. Zatrzymaj się i uporządkuj sygnały.'),('Wytrwałość po wysiłku. Zachowaj czujność i zadbaj o siły.','Zmęczenie utrudnia ocenę. Zrób miejsce na odpoczynek.'),('Ciężar wielu zobowiązań. Ustal, co możesz odłożyć.','Ciężar zaczyna się rozkładać. Oddaj lub zakończ zbędne zadanie.'),('Ciekawość i próba nowego działania. Ucz się przez doświadczenie.','Rozbieg bez przygotowania. Zacznij od prostego ćwiczenia.'),('Odwaga i ruch naprzód. Zwróć uwagę na tempo.','Porywczość rozprasza energię. Ustal, kiedy się zatrzymasz.'),('Pewność siebie i życzliwa inicjatywa. Stwórz innym przestrzeń.','Porównywanie się osłabia swobodę. Wróć do własnego rytmu.'),('Kierowanie wspólnym wysiłkiem. Połącz wizję z odpowiedzialnością.','Dominacja zawęża współpracę. Wysłuchaj innego sposobu działania.')]),
'cups':('Kielichów','odczucia',[
('Otwartość na nowe odczucie. Daj mu miejsce bez pośpiechu.','Emocja pozostaje niewypowiedziana. Spróbuj ją spokojnie nazwać.'),('Wzajemność i spotkanie. Sprawdź, co obie strony wnoszą.','Brak równowagi w wymianie. Porozmawiaj o oczekiwaniach.'),('Wspólna radość i współpraca. Korzystaj z różnych perspektyw.','Nadmiar bodźców lub wykluczenie. Przywróć miejsce każdemu głosowi.'),('Zatrzymanie i namysł nad ofertą. Zauważ możliwość obok siebie.','Powrót zainteresowania. Przyjrzyj się temu, co wcześniej pominięto.'),('Uwaga skupiona na stracie. Zobacz także to, co pozostało.','Stopniowe odzyskiwanie oparcia. Uznaj doświadczenie i zrób krok dalej.'),('Pamięć i wcześniejsze doświadczenia. Sprawdź, co nadal może służyć.','Idealizacja przeszłości. Zestaw wspomnienie z teraźniejszością.'),('Wiele wyobrażonych możliwości. Wybierz jedną do sprawdzenia.','Porządkowanie fantazji. Oddziel pragnienie od wykonalnego planu.'),('Odejście od układu, który przestał wystarczać. Nazwij potrzebę zmiany.','Wahanie przed odejściem. Sprawdź, czego jeszcze szukasz w tym miejscu.'),('Zadowolenie i docenienie tego, co jest. Zauważ źródło satysfakcji.','Spełnienie nie przynosi oczekiwanej treści. Przyjrzyj się potrzebom.'),('Poczucie wspólnoty i zgodności. Zadbaj o to, co je podtrzymuje.','Obraz harmonii ukrywa różnice. Daj im bezpieczne miejsce.'),('Wrażliwa ciekawość i nowa wiadomość. Przyjmij zaskoczenie.','Niedojrzałe oczekiwanie. Sprawdź, co naprawdę zostało przekazane.'),('Podążanie za odczuciem. Połącz inspirację z uważnością na innych.','Idealny obraz przesłania szczegóły. Sprawdź zamiar w działaniu.'),('Empatia i uważne słuchanie. Daj odczuciom formę.','Cudze emocje zalewają własne. Zadbaj o granice.'),('Spokojne obchodzenie się z emocjami. Zachowaj życzliwy dystans.','Tłumienie lub sterowanie odczuciami. Nazwij je bez nacisku.')]),
'swords':('Mieczy','myślenie',[
('Jasne rozróżnienie i nowa myśl. Sformułuj proste pytanie.','Niejasny język rozcina zbyt wiele. Doprecyzuj pojęcia.'),('Dwie równoważące się możliwości. Sprawdź brakującą informację.','Odwlekanie wyboru staje się ciężarem. Ustal kryterium decyzji.'),('Trudna prawda i rozdzielenie. Nazwij to, co boli lub nie pasuje.','Porządkowanie bolesnego doświadczenia. Daj czas na zrozumienie.'),('Przerwa i regeneracja uwagi. Odłóż na chwilę analizę.','Przeciągnięte napięcie. Zaplanuj odpoczynek przed kolejną próbą.'),('Wygrana może kosztować zbyt wiele. Sprawdź skutek sporu.','Możliwość wyjścia z konfliktu. Zrezygnuj z niepotrzebnej walki.'),('Przejście do spokojniejszego miejsca. Zabierz ze sobą potrzebne wnioski.','Ciężar wcześniejszego etapu opóźnia ruch. Wybierz, co zostawić.'),('Strategia i niepełny obraz. Sprawdź, czego nie uwzględnia plan.','Ujawnienie pominięcia. Przywróć przejrzystość działania.'),('Poczucie ograniczenia. Rozróżnij rzeczywistą przeszkodę od założenia.','Dostrzegasz przestrzeń wyboru. Spróbuj małego ruchu.'),('Natrętna myśl i niepokój. Zapisz obawę, aby przyjrzeć się jej z dystansu.','Napięcie może słabnąć. Poszukaj wspierającego sposobu rozmowy.'),('Kres przeciążonego układu. Pozwól zakończyć wyczerpany etap.','Powolne podnoszenie się po zakończeniu. Nie wymagaj natychmiastowego tempa.'),('Dociekliwość i czujna obserwacja. Zadawaj precyzyjne pytania.','Pytania stają się osądem. Najpierw sprawdź informację.'),('Szybka argumentacja i zdecydowanie. Pozostaw chwilę na sprawdzenie.','Pośpiech wniosku wyprzedza dane. Zatrzymaj się przy przesłankach.'),('Niezależna ocena i czytelne granice. Oddziel treść od tonu.','Nadmierna surowość zawęża spojrzenie. Dodaj kontekst.'),('Porządek myślenia i odpowiedzialny osąd. Wyjaśnij regułę decyzji.','Reguła służy przewadze zamiast jasności. Sprawdź jej symetrię.')]),
'pentacles':('Denarów','materia',[
('Konkretny zasób i szansa na rozpoczęcie. Zadbaj o materialną podstawę.','Możliwość wymaga przygotowania. Sprawdź dostępne środki.'),('Równoważenie zadań. Dobierz rytm do swoich możliwości.','Żonglowanie staje się przeciążeniem. Zmniejsz liczbę spraw.'),('Rzemiosło i współpraca. Pokaż pracę, aby zebrać rzeczową uwagę.','Brak wspólnego standardu. Uzgodnij sposób sprawdzania efektu.'),('Zachowanie zasobu i kontrola. Zastanów się, ile ochrony jest potrzebne.','Nadmierne trzymanie lub rozrzutność. Przywróć proporcje.'),('Poczucie braku i wyłączenia. Zauważ dostępne wsparcie.','Pojawia się oparcie. Przyjmij drobną pomoc lub nowy zasób.'),('Wymiana i udzielanie pomocy. Sprawdź równowagę dawania i przyjmowania.','Nierówna zależność. Nazwij warunki wymiany.'),('Ocena powolnego wzrostu. Porównaj nakład pracy z kierunkiem rozwoju.','Niecierpliwość wobec procesu. Sprawdź, czy metoda wymaga zmiany.'),('Ćwiczenie i staranne rzemiosło. Doskonal jedną umiejętność.','Powtarzanie bez uwagi. Zmień sposób ćwiczenia lub odpocznij.'),('Samodzielność i docenienie efektu pracy. Zadbaj o jakość otoczenia.','Zewnętrzny efekt nie daje oparcia. Wróć do tego, co Ci służy.'),('Trwała podstawa i dziedziczone zasoby. Zobacz szerszy układ powiązań.','Utrwalony wzór wymaga przeglądu. Sprawdź, co warto zachować.'),('Cierpliwa nauka i konkretna próba. Przyjrzyj się szczegółowi.','Plan bez praktyki. Zacznij od mierzalnego ćwiczenia.'),('Systematyczna praca i niezawodność. Utrzymaj rozsądne tempo.','Rutyna stała się zastoju przyczyną. Zmień jeden element metody.'),('Troska o warunki i praktyczna zaradność. Połącz wygodę z użytecznością.','Troska wyczerpuje zasoby. Uwzględnij także własne potrzeby.'),('Dojrzałe gospodarowanie zasobami. Buduj coś, co można utrzymać.','Kontrola zasobów przesłania cel. Sprawdź, czemu służy gromadzenie.')])}
raw=json.load(open(r/'provenance.json'));cards=[]
rank=['','As','Dwójka','Trójka','Czwórka','Piątka','Szóstka','Siódemka','Ósemka','Dziewiątka','Dziesiątka','Paź','Rycerz','Królowa','Król']
for v in raw:
 if v['id']=='back':continue
 key=v['id']
 if key[0].isdigit():
  n=int(key[:2]);name,up,rev,theme=major[n];category='Wielkie Arkana';order=n
 else:
  suit,n=key.split('_');n=int(n);su,theme,meanings=suits[suit];name=rank[n]+' '+su;up,rev=meanings[n-1];category=su;order=22+list(suits).index(suit)*14+n-1
 cards.append({'id':key,'name':name,'category':category,'order':order,'upright':up,'reversed':rev,'theme':theme,'model':'res://assets/tarot/models/'+key+'.glb','art_source':v['source'],'art_license':v['license']})
cards.sort(key=lambda c:c['order']);assert len(cards)==78;assert len({c['id'] for c in cards})==78
(r/'cards.json').write_text(json.dumps(cards,ensure_ascii=False,indent=2))
(r/'README.md').write_text('''# Tarot: komplet 78 kart\n\nGrafika: Pamela Colman Smith, Rider–Waite–Smith, oryginalne wydanie Roses & Lilies (1909), domena publiczna według metadanych Wikimedia Commons. Źródła i sumy kontrolne w provenance.json. Żadnych współczesnych przemalowań.\n\nInterpretacje: autorskie, krótkie teksty po polsku inspirowane symboliką ilustracji. Nie są przekładem książki Waite'a ani prognozą zdarzeń. Układ jest narzędziem refleksji. W szczególności nie stanowi dowodu odczytania Manuskryptu.\n\nSilnik działa lokalnie bez konta i internetu. Czyta pola 1–3 lub 1–5 od lewej do prawej; bierze pod uwagę odwrócenie karty. Karty poza polami nie są dopisywane do interpretacji. Układ i wynik zapisują się w projekcie.\n''')
print('Tarot catalog:',len(cards))
