import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import * as T from '../public/vendor/three.module.js';import {MeshoptDecoder} from '../public/vendor/meshopt_decoder.mjs';
const ctx=vm.createContext({console,TextDecoder,TextEncoder,ArrayBuffer,Uint8Array,Float32Array,Uint16Array,Uint32Array,URL,Blob,setTimeout,clearTimeout}),modules=new Map();
async function moduleFor(name){if(modules.has(name))return modules.get(name);let m;if(name==='three'){m=new vm.SyntheticModule(Object.keys(T),function(){for(const[k,v]of Object.entries(T))this.setExport(k,v);},{context:ctx});modules.set(name,m);}else{m=new vm.SourceTextModule(fs.readFileSync(new URL('../public/vendor/'+name,import.meta.url),'utf8'),{context:ctx});modules.set(name,m);await m.link(s=>moduleFor(s==='three'?s:s.replace('./','')));}return m;}
const lm=await moduleFor('GLTFLoader.js');await lm.evaluate();const loader=new lm.namespace.GLTFLoader().setMeshoptDecoder(MeshoptDecoder);const manifest=JSON.parse(fs.readFileSync(new URL('../public/assets/volumes.json',import.meta.url),'utf8')),fixtures=new Map();let triangles=0;
for(const file of ['assets/garden-room.glb',...manifest.map(m=>m.model)]){const b=fs.readFileSync(new URL('../public/'+file,import.meta.url)),g=await loader.parseAsync(b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength),'');fixtures.set(file,g.scene);g.scene.updateMatrixWorld(true);let count=0;g.scene.traverse(o=>{if(o.isMesh){count++;assert.ok([...o.geometry.attributes.position.array].every(Number.isFinite));if(o.geometry.index)assert.ok([...o.geometry.index.array].every(i=>i<o.geometry.attributes.position.count));triangles+=(o.geometry.index?.count||o.geometry.attributes.position.count)/3;}});assert.ok(count>0);if(file.includes('/volume')){const scan=file.match(/s\d{4}/)[0],root=g.scene.getObjectByName('PLANT_'+scan),size=new T.Box3().setFromObject(root).getSize(new T.Vector3());assert.ok(root);assert.ok(root.children.length>=2);const plant=manifest.find(m=>m.scan===scan)?.category==='Rośliny';assert.ok(size.y>(plant?1:.25)&&size.x>.2&&size.z>.05,file+' has nonzero exhibition extents');}}
console.log('PASS actual GLTFLoader + meshopt decoder:',manifest.length,'plants, shared garden, finite vertices/indices, semantic nodes, 3D extents;',triangles,'triangles.');
const html=fs.readFileSync(new URL('../public/garden.html',import.meta.url),'utf8'),js=fs.readFileSync(new URL('../public/garden.js',import.meta.url),'utf8'),ids=new Map([...html.matchAll(/id="([^"]+)"/g)].map(x=>['#'+x[1],{append(){},getBoundingClientRect(){return{width:1000,height:800};}}]));for(const x of js.matchAll(/\$\('#([^']+)'\)/g))assert.ok(ids.has('#'+x[1]),x[1]);
const storage=new Map(),canvas=()=>({getContext:()=>({fillRect(){},fillText(){}}),addEventListener(){}});class Renderer{constructor(){this.domElement=canvas();this.xr={setReferenceSpaceType(){},getController:()=>new T.Group(),isPresenting:false};}setPixelRatio(){}setSize(){}setAnimationLoop(fn){this.frame=fn;}render(){}}class Orbit{constructor(){this.target=new T.Vector3();}update(){}}
const c=vm.createContext({console,devicePixelRatio:1,navigator:{},ResizeObserver:class{observe(){}},localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v)},fetch:async url=>({json:async()=>manifest}),document:{querySelector:s=>{assert.ok(ids.has(s),s);return ids.get(s);},createElement:t=>t==='canvas'?canvas():{}}});
const m=new vm.SourceTextModule(js+'\nexport {select,visit,rotate,reset,release,plants,hands,camera,rig,loadBatch};',{context:c});await m.link(async name=>{const exp=name==='three'?{...T,WebGLRenderer:Renderer,TextureLoader:class{async loadAsync(){return new T.Texture({width:600,height:800});}}}:name.includes('meshopt_decoder')?{MeshoptDecoder}:name.includes('GLTFLoader')?{GLTFLoader:class{setMeshoptDecoder(){return this;}async loadAsync(path){assert.ok(fixtures.has(path),path);return {scene:fixtures.get(path).clone(true)};}}}:name.includes('vr-notebook')?{VRNotebook:class{targets(){return [];}hover(){}frame(){}}}:{OrbitControls:Orbit};return new vm.SyntheticModule(Object.keys(exp),function(){for(const[k,v]of Object.entries(exp))this.setExport(k,v);},{context:c});});await m.evaluate();const a=m.namespace;assert.equal(a.plants.length,10);a.select(8);a.visit();const target=a.plants[8].getWorldPosition(new T.Vector3());assert.ok(Math.abs(a.camera.position.z-target.z-2.4)<1e-6);const q=a.plants[8].quaternion.clone();a.rotate(Math.PI);assert.ok(Math.abs(a.plants[8].quaternion.angleTo(q)-Math.PI)<1e-6);assert.equal(JSON.parse(storage.get('voynich-garden-01')).length,10);const h=a.hands[0],p=a.plants[8];h.controller.position.set(1,1,1);h.controller.attach(p);h.held=p;p.updateWorldMatrix(true,false);const before=p.getWorldPosition(new T.Vector3());a.release(h);assert.equal(h.held,null);assert.ok(before.distanceTo(p.getWorldPosition(new T.Vector3()))<1e-6);a.reset();assert.ok(p.quaternion.angleTo(q)<1e-6);await a.loadBatch('02');assert.equal(a.plants[0].name,'PLANT_s0014');assert.equal(a.plants.length,10);assert.equal(ids.get('#vr').disabled,true);console.log('PASS actual garden: 180° turn, grip release keeps world position, layout save/reset, batch switch loads separate models, unsupported XR disabled. Renderer/DOM/XR mocked.');
