Failed to connect to bus: Operation not permitted
"use strict";

const state={packet:null,records:[],annotations:new Map(),current:0,selected:null,tool:"select",zoom:1,annotator:"",blind:false,draft:null};
const $=id=>document.getElementById(id);
const els={packetStatus:$("packetStatus"),progressTop:$("progressTop"),recordList:$("recordList"),search:$("searchInput"),packetFile:$("packetFile"),scan:$("scanImage"),overlay:$("overlay"),empty:$("emptyCanvas"),stage:$("canvasStage"),viewport:$("canvasViewport"),recordLabel:$("recordLabel"),selectTool:$("selectTool"),drawTool:$("drawTool"),objectId:$("objectId"),objectClass:$("objectClass"),deleteObject:$("deleteObject"),portGrid:$("portGrid"),relationSource:$("relationSource"),relationType:$("relationType"),relationTarget:$("relationTarget"),relationList:$("relationList"),validation:$("validationList"),zoomValue:$("zoomValue"),coords:$("coordinateReadout"),identity:$("identityDialog"),identityForm:$("identityForm"),annotatorInput:$("annotatorInput")};

function canonicalUniverse(records){return JSON.stringify(records.map(r=>[r.record_id,r.source_sha256]));}
async function sha256(text){const bytes=new TextEncoder().encode(text);const digest=await crypto.subtle.digest("SHA-256",bytes);return [...new Uint8Array(digest)].map(v=>v.toString(16).padStart(2,"0")).join("");}
function storageKey(){return `voynich-blind:${state.packet?.record_universe_sha256}:${state.annotator}`;}
function annotationFor(recordId){if(!state.annotations.has(recordId))state.annotations.set(recordId,{record_id:recordId,source_sha256:state.records.find(r=>r.record_id===recordId).source_sha256,objects:[],occlusions:[]});return state.annotations.get(recordId);}
function currentRecord(){return state.records[state.current];}
function currentAnnotation(){const record=currentRecord();return record?annotationFor(record.record_id):null;}
function save(){if(!state.packet||!state.annotator)return;localStorage.setItem(storageKey(),JSON.stringify({annotations:[...state.annotations.values()],current:state.current}));}
function restore(){const raw=localStorage.getItem(storageKey());if(!raw)return;try{const saved=JSON.parse(raw);state.annotations=new Map((saved.annotations||[]).map(a=>[a.record_id,a]));state.current=Math.min(saved.current||0,state.records.length-1);}catch{localStorage.removeItem(storageKey());}}

async function loadPacket(packet){
  const calculated=await sha256(canonicalUniverse(packet.records||[]));
  if(packet.schema_version!=="1.0"||calculated!==packet.record_universe_sha256||packet.record_count!==(packet.records||[]).length)throw new Error("Packet integrity check failed");
  state.packet=packet;state.records=packet.records;state.annotations=new Map();state.current=0;state.selected=null;
  els.packetStatus.textContent="Packet OK";els.packetStatus.className="status-dot ok";
  els.identity.showModal();
}

function beginSession(){state.annotator=els.annotatorInput.value.trim();state.blind=[...els.identityForm.querySelectorAll('input[name="blind"]')].every(i=>i.checked);if(!state.annotator||!state.blind)return false;restore();renderAll();return true;}
function imageUrl(path){return new URL(`../../../${path}`,location.href).href;}
function setTool(tool){state.tool=tool;els.selectTool.classList.toggle("active",tool==="select");els.drawTool.classList.toggle("active",tool==="draw");els.selectTool.setAttribute("aria-pressed",tool==="select");els.drawTool.setAttribute("aria-pressed",tool==="draw");els.overlay.style.cursor=tool==="draw"?"crosshair":"default";}
function isComplete(annotation){return annotation&&annotation.objects.length>0&&validateRecord(annotation).length===0;}
function renderRecordList(){const query=els.search.value.trim().toLowerCase();els.recordList.textContent="";state.records.forEach((record,index)=>{if(query&&!record.record_id.toLowerCase().includes(query))return;const button=document.createElement("button");button.className=`record-row${index===state.current?" active":""}`;button.innerHTML=`<span class="record-state ${isComplete(state.annotations.get(record.record_id))?"done":""}"></span><span>${record.record_id}</span>`;button.onclick=()=>{state.current=index;state.selected=null;save();renderAll();};els.recordList.append(button);});}
function renderCanvas(){const record=currentRecord();if(!record){els.empty.hidden=false;return;}els.empty.hidden=true;els.recordLabel.textContent=record.record_id;els.scan.src=imageUrl(record.source_path);els.scan.onload=()=>{const maxWidth=Math.max(420,els.viewport.clientWidth-24),maxHeight=Math.max(420,els.viewport.clientHeight-24);const scale=Math.min(maxWidth/record.width,maxHeight/record.height,1);els.scan.style.width=`${record.width*scale}px`;els.scan.style.height=`${record.height*scale}px`;els.stage.style.width=els.scan.style.width;els.stage.style.height=els.scan.style.height;els.overlay.setAttribute("viewBox","0 0 1 1");renderOverlay();applyZoom();};}
function svg(tag,attrs={}){const node=document.createElementNS("http://www.w3.org/2000/svg",tag);Object.entries(attrs).forEach(([k,v])=>node.setAttribute(k,v));return node;}
function renderOverlay(){els.overlay.textContent="";const annotation=currentAnnotation();if(!annotation)return;annotation.objects.forEach(object=>{const [x1,y1,x2,y2]=object.bbox;const group=svg("g",{"data-id":object.local_id});const rect=svg("rect",{x:x1,y:y1,width:x2-x1,height:y2-y1,class:`bbox${state.selected===object.local_id?" selected":""}`});rect.addEventListener("pointerdown",event=>{if(state.tool==="select"){event.stopPropagation();state.selected=object.local_id;renderAll(false);}});const text=svg("text",{x:x1+0.004,y:Math.max(.018,y1+.018),class:"bbox-label"});text.textContent=`${object.local_id} · ${object.class.replaceAll("_"," ")}`;group.append(rect,text);els.overlay.append(group);});if(state.draft){const [x1,y1,x2,y2]=state.draft;els.overlay.append(svg("rect",{x:x1,y:y1,width:x2-x1,height:y2-y1,class:"draft-box"}));}}
function selectedObject(){return currentAnnotation()?.objects.find(o=>o.local_id===state.selected)||null;}
function renderInspector(){const object=selectedObject();els.objectId.value=object?.local_id||"";els.objectClass.disabled=!object;els.objectClass.value=object?.class||"ILLUSTRATION_OBJECT";els.deleteObject.disabled=!object;els.portGrid.querySelectorAll("input").forEach(input=>{input.disabled=!object;input.checked=object?.ports.includes(input.value)||false;});const annotation=currentAnnotation();const options=(annotation?.objects||[]).map(o=>`<option value="${o.local_id}">${o.local_id}</option>`).join("");els.relationSource.innerHTML=options;els.relationTarget.innerHTML=options;if(object)els.relationSource.value=object.local_id;renderRelations();renderValidation();}
function renderRelations(){const annotation=currentAnnotation();if(!annotation?.occlusions.length){els.relationList.textContent="No relations";return;}els.relationList.textContent="";annotation.occlusions.forEach((r,index)=>{const row=document.createElement("div");row.className="relation-item";row.innerHTML=`<span>${r.source_id} ${r.relation.replaceAll("_"," ").toLowerCase()} ${r.target_id}</span>`;const remove=document.createElement("button");remove.textContent="Remove";remove.onclick=()=>{annotation.occlusions.splice(index,1);save();renderAll(false);};row.append(remove);els.relationList.append(row);});}
function validateRecord(annotation){const issues=[];const ids=new Set();annotation.objects.forEach(o=>{if(ids.has(o.local_id))issues.push(`Duplicate object ${o.local_id}`);ids.add(o.local_id);const [x1,y1,x2,y2]=o.bbox;if(!(x1>=0&&y1>=0&&x2<=1&&y2<=1&&x1<x2&&y1<y2))issues.push(`Invalid box ${o.local_id}`);});annotation.occlusions.forEach(r=>{if(!ids.has(r.source_id)||!ids.has(r.target_id))issues.push("Relation has missing endpoint");if(r.source_id===r.target_id)issues.push("Self relation is forbidden");});return issues;}
function renderValidation(){const annotation=currentAnnotation();const issues=annotation?validateRecord(annotation):["No active record"];els.validation.classList.toggle("error",issues.length>0);els.validation.textContent=issues.length?issues.join(" · "):"No issues";}
function renderProgress(){const done=state.records.filter(r=>isComplete(state.annotations.get(r.record_id))).length;els.progressTop.textContent=`${done} / ${state.records.length}`;}
function renderAll(canvas=true){renderRecordList();if(canvas)renderCanvas();else renderOverlay();renderInspector();renderProgress();}
function normalizedPoint(event){const rect=els.overlay.getBoundingClientRect();return [Math.max(0,Math.min(1,(event.clientX-rect.left)/rect.width)),Math.max(0,Math.min(1,(event.clientY-rect.top)/rect.height))];}
function nextObjectId(annotation){let n=1;while(annotation.objects.some(o=>o.local_id===`OBJ-${String(n).padStart(4,"0")}`))n++;return `OBJ-${String(n).padStart(4,"0")}`;}
function applyZoom(){els.stage.style.transform=`scale(${state.zoom})`;els.zoomValue.textContent=`${Math.round(state.zoom*100)}%`;}
function exportSubmission(){if(!state.packet||!state.annotator||!state.blind)return;state.records.forEach(r=>annotationFor(r.record_id));const submission={schema_version:"1.0",annotation_id:`${state.packet.packet_id}-${new Date().toISOString()}`,annotator_id:state.annotator,blindness:{other_annotation_unseen:true,automated_candidates_unseen:true,model_predictions_unseen:true,hypothesis_labels_unseen:true,split_assignment_unseen:true},records:state.records.map(r=>state.annotations.get(r.record_id))};const blob=new Blob([JSON.stringify(submission,null,2)+"\n"],{type:"application/json"});const link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download=`${state.packet.packet_id}-${state.annotator}.annotation.json`;link.click();URL.revokeObjectURL(link.href);}

els.overlay.addEventListener("pointerdown",event=>{if(state.tool!=="draw"||!currentAnnotation())return;els.overlay.setPointerCapture(event.pointerId);const start=normalizedPoint(event);state.draft=[...start,...start];renderOverlay();const move=e=>{const end=normalizedPoint(e);state.draft=[Math.min(start[0],end[0]),Math.min(start[1],end[1]),Math.max(start[0],end[0]),Math.max(start[1],end[1])];els.coords.textContent=`x: ${state.draft[0].toFixed(3)}  y: ${state.draft[1].toFixed(3)}  w: ${(state.draft[2]-state.draft[0]).toFixed(3)}  h: ${(state.draft[3]-state.draft[1]).toFixed(3)}`;renderOverlay();};const up=e=>{els.overlay.removeEventListener("pointermove",move);els.overlay.removeEventListener("pointerup",up);const box=state.draft;state.draft=null;if(box&&box[2]-box[0]>.002&&box[3]-box[1]>.002){const annotation=currentAnnotation(),id=nextObjectId(annotation);annotation.objects.push({local_id:id,class:"ILLUSTRATION_OBJECT",bbox:box.map(v=>Number(v.toFixed(6))),ports:[]});state.selected=id;save();}renderAll(false);};els.overlay.addEventListener("pointermove",move);els.overlay.addEventListener("pointerup",up);});
els.overlay.addEventListener("pointermove",event=>{if(state.draft)return;const [x,y]=normalizedPoint(event);els.coords.textContent=`x: ${x.toFixed(3)}  y: ${y.toFixed(3)}  w: 0  h: 0`;});
els.objectClass.onchange=()=>{const o=selectedObject();if(o){o.class=els.objectClass.value;save();renderAll(false);}};
els.portGrid.onchange=()=>{const o=selectedObject();if(o){o.ports=[...els.portGrid.querySelectorAll("input:checked")].map(i=>i.value);save();renderAll(false);}};
els.deleteObject.onclick=()=>{const a=currentAnnotation(),id=state.selected;if(!a||!id)return;a.objects=a.objects.filter(o=>o.local_id!==id);a.occlusions=a.occlusions.filter(r=>r.source_id!==id&&r.target_id!==id);state.selected=null;save();renderAll(false);};
$("addRelation").onclick=()=>{const a=currentAnnotation(),source=els.relationSource.value,target=els.relationTarget.value;if(!a||!source||!target||source===target)return;a.occlusions.push({source_id:source,target_id:target,relation:els.relationType.value});save();renderAll(false);};
els.selectTool.onclick=()=>setTool("select");els.drawTool.onclick=()=>setTool("draw");els.search.oninput=renderRecordList;$("zoomIn").onclick=()=>{state.zoom=Math.min(2,state.zoom+.1);applyZoom();};$("zoomOut").onclick=()=>{state.zoom=Math.max(.5,state.zoom-.1);applyZoom();};$("exportButton").onclick=exportSubmission;$("loadPacketButton").onclick=()=>els.packetFile.click();els.packetFile.onchange=async()=>{try{await loadPacket(JSON.parse(await els.packetFile.files[0].text()));}catch(error){els.packetStatus.textContent=error.message;els.packetStatus.className="status-dot error";}};
els.identityForm.addEventListener("submit",event=>{if(!beginSession()){event.preventDefault();return;}save();});

async function boot(){const params=new URLSearchParams(location.search);const source=params.get("packet")||"../packets/annotator-a.packet.json";try{const response=await fetch(source);if(!response.ok)throw new Error(`Packet HTTP ${response.status}`);await loadPacket(await response.json());}catch(error){els.packetStatus.textContent="Load packet";els.packetStatus.className="status-dot error";els.validation.textContent=error.message;}}
boot();
