from pathlib import Path
from PIL import Image,ImageCms
import json,csv,hashlib,html,io
R=Path(__file__).resolve().parent;ROOT=R.parent;OUT=R/'audit';(OUT/'thumbs').mkdir(parents=True,exist_ok=True)
A=json.load(open(ROOT/'voynich-3d/public/assets/atlas.json'))['pages'];cat=json.load(open(ROOT/'quest-native/assets/catalog.json'));details=json.load(open(R/'details/PROGRESS.json'));rows=[];cards=[]
for p in A:
 f=ROOT/'quest-native/assets/source_pixels'/(p['id']+'.jpgbin');sha=hashlib.sha256(f.read_bytes()).hexdigest();im=Image.open(f);profile=ImageCms.getProfileDescription(ImageCms.ImageCmsProfile(io.BytesIO(im.info['icc_profile']))).strip();assert sha==p['sha256']
 models=[m for m in cat if m['scan']==p['id']];vol=[m for m in models if 'relief' not in m['category'].lower()];status='SOURCE_OK; CANDIDATE_MODELS' if models else 'SOURCE_OK; COVER_IN_CODEX'
 row={'scan_id':p['id'],'folio':p['label'],'width':p['width'],'height':p['height'],'sha256':sha,'icc':profile,'category':('Tekst i drobne znaki' if p['id']=='s0137' else p['category']),'model_count':len(models),'model_ids':'|'.join(m.get('id',m['scan']) for m in models),'semantic_inventory_complete':False,'all_individual_drawings_verified':False,'status':status};rows.append(row)
 thumb=im.copy();thumb.thumbnail((340,430));thumb.convert('RGB').save(OUT/'thumbs'/(p['id']+'.jpg'),quality=82)
 notes=[]
 if p['id']=='s0137':notes.append('Korekta: f76r jest stroną tekstową; dawna kategoria scen była myląca.')
 if p['id'] in ['s0119','s0206','s0157']:notes.append('Dodano osobne przybliżone bryły detali oraz relief całej strony.')
 if p['id']=='s0158':notes.append('Relief 2.5D + dziewięć rozet przestrzennych. Trzynaście pasm i wybrane formy architektoniczne. Brak pełnej ręcznej anotacji wszystkich ornamentów.')
 cards.append('<article data-category="'+html.escape(row['category'])+'"><h2>'+p['id']+' · f'+html.escape(p['label'])+'</h2><img loading="lazy" src="thumbs/'+p['id']+'.jpg"/><p>'+html.escape(row['category'])+' · '+str(len(models))+' zestawów</p><p>'+html.escape(' '.join(notes))+'</p><small>'+sha+'</small><details><summary>Modele i stan weryfikacji</summary><ul>'+''.join('<li>'+html.escape(m.get('id',m['scan'])+' — '+m['category'])+'</li>' for m in models)+'</ul><p>Spis pojedynczych rysunków: NIEPOTWIERDZONY. Relief zachowuje obraz, nie poświadcza kompletnej rekonstrukcji bryłowej.</p></details></article>')
with (OUT/'PAGE_MANIFEST.csv').open('w',newline='') as f:
 w=csv.DictWriter(f,fieldnames=rows[0].keys());w.writeheader();w.writerows(rows)
(OUT/'PAGE_MANIFEST.json').write_text(json.dumps(rows,ensure_ascii=False,indent=2))
coverage={'status':'CANONICAL_ATLAS_IN_PROGRESS','canonical_basis':'voynich-3d/public/assets/atlas.json; 206-scan atlas, extended without replacing historical records','manifest_pages':206,'sources_verified':206,'embedded_sRGB_profiles':206,'pages_with_model_candidates':len({m['scan'] for m in cat}),'catalog_ensembles':len(cat),'new_candidates':71,'new_batches':[21,22,23,24,25,26,27,28],'complete_semantic_inventories_verified':0,'verified_individual_object_total':None,'text_geometry_complete':False,'cross_page_scientific_relations_tested':0,'source_conflicts_unresolved':0,'notes':['Model counts are not counts of illustrations.','31 full-page reliefs close presentation gaps, not semantic annotation gaps.','Automated contours include text/noise; no claim that every drawing is separately identified.','Full 206 scan order is preserved; historical folio collation and fold mechanisms are not reconstructed.']}
(OUT/'ATLAS_COVERAGE.json').write_text(json.dumps(coverage,ensure_ascii=False,indent=2))
objects=[]
for m in details:
 p=next(p for p in A if p['id']==m['scan']);b=m['source_bbox_norm'];objects.append({'object_id':m['id'],'parent_id':m['scan'],'folio':m['folio'],'source_sha256':m['source_sha256'],'bbox_norm':b,'bbox_px':[round(b[0]*p['width']),round(b[1]*p['height']),round(b[2]*p['width']),round(b[3]*p['height'])],'class':'candidate_marginal_or_flow_form','status':'CANDIDATE_DEPTH','model':m['model'],'note':m['description']})
(OUT/'ILLUSTRATION_OBJECTS.json').write_text(json.dumps(objects,ensure_ascii=False,indent=2))
(OUT/'CHANGELOG.md').write_text('2026-09-27 / 0.3\n\n- Zweryfikowano SHA-256, wymiary i profile sRGB wszystkich 206 skanów. Użyto kanonicznych napraw dla uszkodzonych załączników.\n- Dodano 71 kandydatów modeli w Blenderze.\n- f76r: korekta kategorii na tekstową w audycie.\n- 2.5D i 3D rozet: geometria głębi jest interpretacyjna.\n- Małe postacie, forma zwierzęca, naczynie, koliste formy i cztery formy przepływowe mają osobne bryły.\n- Nie stwierdzono ukończenia spisu wszystkich rysunków. Potrzebna niezależna kontrola obiekt po obiekcie.\n- Żadna relacja geometryczna nie jest traktowana jako odczyt tekstu lub dowód funkcji.\n')
(OUT/'index.html').write_text('''<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Manuskrypt — audyt 206 skanów</title><style>body{margin:0;background:#101f29;color:#eee;font:17px system-ui}header{padding:32px;max-width:1100px}h1{font-size:36px}input,select{padding:14px;font:inherit;background:#213b49;color:white;border:1px solid #537483}main{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:20px;padding:24px}article{background:#203540;padding:16px;border-radius:12px}img{width:100%;height:360px;object-fit:contain}h2{font-size:19px}small{font:11px monospace;overflow-wrap:anywhere}details{margin-top:16px}a{color:#9be2da}</style><header><h1>206 skanów · audyt modeli 0.3</h1><p>254 zestawy w katalogu, w tym 71 nowych modeli. To liczba zestawów, nie zweryfikowanych pojedynczych ilustracji.</p><p>Każda strona jest dostępna w kodeksie i próbniku pełnej rozdzielczości. Głębia modeli jest interpretacją; pełny spis drobnych rysunków nadal wymaga kontroli.</p><input id="q" placeholder="Szukaj folio lub modelu"><select id="c"><option value="">Wszystkie kategorie</option>'''+''.join('<option>'+html.escape(x)+'</option>' for x in sorted(set(r['category'] for r in rows)))+'''</select><p><a href="PAGE_MANIFEST.csv">Manifest CSV</a> · <a href="ATLAS_COVERAGE.json">Dokładny stan pokrycia</a></p></header><main>'''+''.join(cards)+'''</main><script>const cards=[...document.querySelectorAll('article')];function filter(){cards.forEach(a=>a.hidden=!(a.textContent.toLowerCase().includes(q.value.toLowerCase())&&(!c.value||a.dataset.category===c.value)))}q.oninput=filter;c.onchange=filter;</script>''')
print(coverage)
